USE [master]
GO
DROP DATABASE IF EXISTS AssetsManagement 
GO

CREATE DATABASE [AssetsManagement]
GO

USE [AssetsManagement]

IF NOT EXISTS (select loginname from master.dbo.syslogins where name = 'am_user') 
	BEGIN 
		CREATE LOGIN am_user WITH PASSWORD=N'Pa$$W0Rd', DEFAULT_DATABASE=[AssetsManagement], 
			DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF 
		
	END
GO 




CREATE USER am_user FOR LOGIN am_user WITH DEFAULT_SCHEMA=[dbo]
GO

EXEC sp_addrolemember N'db_owner', N'am_user'
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Address](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[City] [int] NOT NULL,
	[Street] [varchar](50) NOT NULL,
	[HouseNumber] [int] NOT NULL,
 CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[City](
	[Symbol] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
(
	[Symbol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Owner](
	[Id] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Owner] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Tenant](
	[Id] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Tenant] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Asset](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Address] [int] NOT NULL,
	[Owner] [int] NOT NULL,
 CONSTRAINT [PK_Asset] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Asset]  WITH CHECK ADD  CONSTRAINT [FK_Asset_Address] FOREIGN KEY([Address])
REFERENCES [dbo].[Address] ([Id])
GO

ALTER TABLE [dbo].[Asset] CHECK CONSTRAINT [FK_Asset_Address]
GO

ALTER TABLE [dbo].[Asset]  WITH CHECK ADD  CONSTRAINT [FK_Asset_Owner] FOREIGN KEY([Owner])
REFERENCES [dbo].[Owner] ([Id])
GO

ALTER TABLE [dbo].[Asset] CHECK CONSTRAINT [FK_Asset_Owner]
GO

CREATE TABLE [dbo].[RentalAgreement](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Asset] [int] NOT NULL,
	[Tenant] [int] NOT NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
 CONSTRAINT [PK_RentalAgreement] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RentalAgreement]  WITH CHECK ADD  CONSTRAINT [FK_RentalAgreement_Asset] FOREIGN KEY([Asset])
REFERENCES [dbo].[Asset] ([Id])
GO

ALTER TABLE [dbo].[RentalAgreement] CHECK CONSTRAINT [FK_RentalAgreement_Asset]
GO

ALTER TABLE [dbo].[RentalAgreement]  WITH CHECK ADD  CONSTRAINT [FK_RentalAgreement_Tenant] FOREIGN KEY([Tenant])
REFERENCES [dbo].[Tenant] ([Id])
GO

ALTER TABLE [dbo].[RentalAgreement] CHECK CONSTRAINT [FK_RentalAgreement_Tenant]
GO
USE [master]
GO





